### ISSUE TITLE
[ENHANCEMENT] Enhance performance

### ISSUE THREAD

**Issue by scalalang2** [scalalang2/golang-fifo#12]
## Motivation
Let's explore a way to enhance the performance of this implementation 🤔

**Comment by scalalang2** [comment]
To minimize GC overhead, we can use [this technique](https://github.com/vitessio/vitess/blob/main/go/hack/hack.go) used at vitess, which is a sharded database compatible with MySQL

**Comment by sylr** [comment]
See https://github.com/golang/go/issues/62483

**Comment by scalalang2** [comment]
@sylr thanks for sharing it 👍 
I'll follow this up.

**Comment by scalalang2** [comment]
See also [go-ethereum/common/lru/blob_lru.go](https://github.com/ethereum/go-ethereum/blob/f1794ba2788baf34489847bfa9ca00e067507db0/common/lru/blob_lru.go)
