### ISSUE TITLE
Implementation of the `ShardedCache`

### ISSUE THREAD

**Issue by scalalang2** [scalalang2/golang-fifo#24]
## Motivation
refer : [elastic/go-freelru](https://github.com/elastic/go-freelru)

They provides `ShardedLRU` which provides sharded, concurrency-safe implementation but it uses an approximate LRU algorithm.

**Comment by ccoVeille** [comment]
The issue was closed, but what but PR or commit implemented it?

Having the reference would be better I think

**Comment by scalalang2** [comment]
This was unintentionally closed, I repoened this, thx : )

**Comment by scalalang2** [comment]
@copilot please help!
