### ISSUE TITLE
OnEvictCallback called for non-evictions

### ISSUE THREAD

**Issue by costela** [scalalang2/golang-fifo#36]
Currently, the `OnEvictCallback` callback is called for [evictions](https://github.com/scalalang2/golang-fifo/blob/59489b85135694b0c1d0d43ea3f1f4de2038c0dd/s3fifo/s3fifo.go#L114) - as expected - but also for [expirations](https://github.com/scalalang2/golang-fifo/blob/59489b85135694b0c1d0d43ea3f1f4de2038c0dd/s3fifo/s3fifo.go#L259) (based on TTL) *and* [manual removals](https://github.com/scalalang2/golang-fifo/blob/59489b85135694b0c1d0d43ea3f1f4de2038c0dd/s3fifo/s3fifo.go#L153).

Further, the current `OnEvictCallback` signature does not allow differentiate which of these cases happened.

I propose making a breaking change and either:
- adding separate callbacks
- adding a "cause" parameter to `OnEvictCallback`

Any of these seem acceptable? If yes, I'd cook up a PR.

**Comment by scalalang2** [comment]
Hello @costela
I'm pleased to see your contribution 🙇 

I think that adding a parameter to the function seems fine.

```go
type OnEvictCallback[K comparable, V any] func(key K, value V, expired bool)
```

The name expired is arbitrarily chosen by me, please suggest a name that makes sense more.

**Comment by costela** [comment]
A first pass is at https://github.com/scalalang2/golang-fifo/pull/37

PTAL :pray:

**Comment by scalalang2** [comment]
Thank you for your work. Once it's merged, I'll tag it with a new release 👍
