### ISSUE TITLE
Enquiry : reasoning behind using a single mutex in sieve.go

### ISSUE THREAD

**Issue by SHIVAYspec** [scalalang2/golang-fifo#38]
Just an enquiry
What is the reason for using a single Mutex in sieve.go? Did you consider dividing it into shards and keeping one Mutex per shard?
It seems like it would decrease contention on the Mutex if the system has multiple processors.
Thanks for your time in advance.

**Comment by scalalang2** [comment]
I had opened an issue related with your inquiry. #24 

I won't be able to work on it right now, but I plan to develop it after September. 
If you want to take this issue and contribute, then I would appreciate it 😄
