### ISSUE TITLE
Feedback on a statement

### ISSUE THREAD

**Issue by 1a1a11a** [scalalang2/golang-fifo#6]
This is awesome work! 

One suggestion on the result. It mentions that "SIEVE is about 10% more efficient than a simple LRU cache", which I think is not very accurate. 
When comparing the miss ratio, we usually state relative numbers. For example, reducing the mass ratio from 2% to 1% is a (2-1)/2=50% improvement because the backend load is reduced by 50%. Moreover, the mean latency is about proportional to the mass ratio and has a similar reduction. :) 

BTW, do you have results for S3-FIFO as well?

**Comment by scalalang2** [comment]
Thank you visiting here 👍 

I understand what you are saying. Increasing efficiency means not only reducing cache misses, but also reducing the demand for heavy operations such as backend database access, which lowers the mean latency.

And also as you said, It seems that I expressed incorrectly the evaluation of miss ratio. it would be correct to express that the SIEVE has improved performance by 30% in comparison with simple LRU cache.

**Comment by scalalang2** [comment]
**S3-FIFO**

As mentioned in paper, It can be done with lock-free data structure which leads to scalability improvement. So that, I am trying to do it with lock-free, **but it doesn't seem easy. 😢 ** I will include the results when It's done

Of course, I have also benchmarked the current implementation, and the results are similar to TinyLFU.

**Comment by scalalang2** [comment]
For others.
He is a first author of S3-FIFO and a second author of SIEVE.

**Comment by 1a1a11a** [comment]
I recently learned that implementing the algorithm efficiently in other languages is not that easy, haha. 

BTW we will include your repo in our planned advertisement. Will that be ok with you?

**Comment by scalalang2** [comment]
> we will include your repo in our planned advertisement. Will that be ok with you?

Absolutely! Thank you so much : )

**Comment by 1a1a11a** [comment]
Awesome!
